# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2e22288b7af3ab7b573552da36d29584bd71f814a4c0d61102ea9784ab39fc2f9a7a3e283f95016fd61f5a29c1eb8a3949a1158cf9349e2e9530136e7126183

test:
  secret_key_base: 89025d42a6bacccf4c215bda6b352d647165f079399d1910ffcf665395d92b8631e94dfe8097ce25061dde07e3120aa16629e668898800d6bb641c7e47f281c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
